### ISSUE TITLE
Todo for demo presentation

### ISSUE THREAD

**Issue by junhoyeo** [connection-youth/connection#3]
- [ ] 모든 페이지 초기화, 렌더링
- [ ] 테스트 데이터 넣기
- [ ] 이전 버전의 페이지 다른 곳으로 올려 두기
- [ ] 네이버 (또는 카카오) 지도 표시하기
- [ ] 모바일 페이지 뷰
- [ ] 모바일 페이지 신청 시 모달
- [ ] 검색의 경우 임시로 프론트엔드 단에서 구현
- [ ] 마크다운 게시글 표시하기

**Comment by junhoyeo** [comment]
<img width="515" alt="스크린샷 2019-12-31 오후 4 28 20" src="https://user-images.githubusercontent.com/32605822/71613557-9592f800-2bea-11ea-864a-b3b9c52f20bf.png">
🚀
